version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: openresty/openresty:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - /var/log/nginx/:/var/log/nginx/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nodejs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ${CERTBOT_EMAIL_ADDRESS} --agree-tos --no-eff-email -d ${CERTBOT_DOMAIN_NAME}  -d www.${CERTBOT_DOMAIN_NAME}

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/${UBUNTU_USERNAME}/filepret/build/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/${UBUNTU_USERNAME}/filepret/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
